enyo.depends(
    "cdv-plugin-fb-connect.js",
    "facebook_js_sdk.js",
    "SMSComposer.js",
    "ImageResizer.js",
    "PushNotification.js",
    "social.js",
    "CDVInstagramPlugin.js",
    "EmailComposer.js"
);