enyo.depends(
	"util.js",
	"$lib/layout",
	"$lib/onyx",
	"$lib/sdk",
	"$lib/Base64.js",
	"css/",
	"App.js",
	"MainView.js",
	"ChuboxItem.js",
	"Chubox.js",
	"ChuboxItemView.js",
	"FormField.js",
	"SignUpForm.js",
	"StartPage.js",
	"ChuFeed.js",
	"ChuView.js",
	"PeopleSelector.js"
);
